Implementa usando PyTorch  e seguindo a documentación un clasificador para o dataset Iris. 


- Son moi similares aos arrays e as matrices
- En PyTorch se utilizan para codificar as entradas, as saídas e os parámetros dos modelos.
- Son similares a os arrays de numpy, salvo polo feito que os tensores pode executarse nunha GPU


In [105]:
import torch
import numpy as np

- Tensores poden ser creados a partires arrays de numpy
- Cando se crean dende numpy, o almacen de memoria é compartido. Modificar a través de numpy tamén modifica o contido do tensor.

In [106]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

arr = np.array([[1, 2, 3], [4, 5, 6]])
x_np = torch.from_numpy(arr)
print(x_np)

tensor([[1, 2, 3],
        [4, 5, 6]])


Desde otro tensor

In [107]:
x_unos = torch.ones_like(x_np) 
print(f"Tensor con unos: \n {x_unos} \n")

x_aleatorio = torch.rand_like(x_np, dtype=torch.float)
print(f"Tensor aleatorio: \n {x_aleatorio} \n")

Tensor con unos: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

Tensor aleatorio: 
 tensor([[0.4219, 0.6145, 0.2044],
        [0.0028, 0.8155, 0.5107]]) 



Al igual que numpy se pueden crear un array de numeros del 0 al 4. Como un range de python, pero más rapido

In [108]:
arra2 = torch.arange(5)

arra3 = torch.zeros(5) # array de 5 elementos
arra4 = torch.zeros([5,3]) # array de 5x3 elementos

 
#  Con rand se xeran valores entre 0 e 1
#  Con randint se xeran int dentro dun rango

x1 = torch.randint(10, size=(20,)) # tensor de 20 elementos con numeros do 0 ao 9
x2 = torch.rand(5,3) # array de 5x3 elementos con valores entre 0 e 1

#### Dimensiones y tamaño

In [109]:
# A partires dun array existente podemos saber o número de dimensións e o tamaño:
#  o método dim() indica o numero de dimensións
#  o método size() indica o tamaño de cada dimensión


arr = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(arr) 
print(arr.dim()) # imprime 2
print(arr.size()) # imprime (2,3: 2 filas, 3 columnas
# pódese indicar a dimensión que se quere consultar
print(arr.size(dim=1)) # imprime 3

tensor([[1, 2, 3],
        [4, 5, 6]])
2
torch.Size([2, 3])
3


#### Reshape

In [110]:
array = torch.arange(1,13) # array con 12 elementos, comenzando en 1
newarr = array.reshape(4, 3) # array con 4 filas e 3 columnas
print(array)
print(newarr)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [111]:
array2 = torch.tensor([[1, 2, 3], [4, 5, 6]])

newarr = array2.reshape(-1)

print(array2)
print(newarr) 

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])


#### Añadir elementos a un tensor


- Non se pode engadir elementos a un tensor despois da creación
- Pero podemos crear un novo tensor que una dous tensor, para iso está a función cat


In [112]:
arr1 = torch.tensor([1, 2, 3])

arr2 = torch.tensor([4, 5, 6])

arr = torch.cat((arr1, arr2))

print(arr) 

tensor([1, 2, 3, 4, 5, 6])


En 2D tamén se pode concatenar, neste caso hai que indicar en que dimensión se van a concatenar co parámetro dim

In [113]:
arr1 = torch.tensor([[1, 2], [3, 4]])
arr2 = torch.tensor([[5, 6], [7, 8]])
arrAumentarColumnas = torch.cat((arr1, arr2), dim=1)
arrAumentarFilas = torch.cat((arr1, arr2), dim=0)

print(arrAumentarColumnas)
print(arrAumentarFilas)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


#### Operaciones con tensores

- Funcionan todas as operacions básicas: + - * / (son operaciones elemento a elemento)

In [114]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([4, 5, 6, 7])
a = x + y
b = x - y
c = x * y
d = x / y


- Las dimensiones deben coincidir, salvo que la operación sea con un entero

In [115]:
x = torch.tensor([1, 2, 3, 4])
a = x + 1
b = x - 2
c = x * 4
d = x / 3

Con booleanos:

In [116]:
x = torch.tensor([1, 2, 3, 4])
a = x ==2
#  a sería [False,  True, False, False]

Un tensor de booleans puede ser usado como máscara para acceder a los elementos

In [117]:
x = torch.tensor([1, 2, 3, 4])
a = x >=3
#  a sería [False, False,  True,  True]
x[a] # é un array que conten os elementos onde a == True
c = x[a] + 4

print(c)

tensor([7, 8])


Función dot:

In [118]:
x = torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))
# x vai valer 7 = 2*2 + 3*1
print(x)

tensor(7)


Producto de matrices: (torch.mm(a, b) ou torch.matmul(a, b) ou @)

In [119]:
a = torch.tensor([[1,2],
                   [3,4]])
b = torch.tensor([[5, 6],
                  [7, 8]])

# tensor([[19, 22],
#        [43, 50]])

print(a@b)

tensor([[19, 22],
        [43, 50]])
