Implementa usando PyTorch  e seguindo a documentación un clasificador para o dataset Iris. 


- Son moi similares aos arrays e as matrices
- En PyTorch se utilizan para codificar as entradas, as saídas e os parámetros dos modelos.
- Son similares a os arrays de numpy, salvo polo feito que os tensores pode executarse nunha GPU


In [30]:
import torch
import numpy as np

- Tensores poden ser creados a partires arrays de numpy
- Cando se crean dende numpy, o almacen de memoria é compartido. Modificar a través de numpy tamén modifica o contido do tensor.

In [31]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

arr = np.array([[1, 2, 3], [4, 5, 6]])
x_np = torch.from_numpy(arr)
print(x_np)

tensor([[1, 2, 3],
        [4, 5, 6]])


Desde otro tensor

In [32]:
x_unos = torch.ones_like(x_np) 
print(f"Tensor con unos: \n {x_unos} \n")

x_aleatorio = torch.rand_like(x_np, dtype=torch.float)
print(f"Tensor aleatorio: \n {x_aleatorio} \n")

Tensor con unos: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

Tensor aleatorio: 
 tensor([[0.5488, 0.9005, 0.0377],
        [0.8353, 0.9318, 0.1642]]) 



Al igual que numpy se pueden crear un array de numeros del 0 al 4. Como un range de python, pero más rapido

In [33]:
arra2 = torch.arange(5)

arra3 = torch.zeros(5) # array de 5 elementos
arra4 = torch.zeros([5,3]) # array de 5x3 elementos

 
#  Con rand se xeran valores entre 0 e 1
#  Con randint se xeran int dentro dun rango

x1 = torch.randint(10, size=(20,)) # tensor de 20 elementos con numeros do 0 ao 9
x2 = torch.rand(5,3) # array de 5x3 elementos con valores entre 0 e 1

#### Dimensiones y tamaño

In [34]:
# A partires dun array existente podemos saber o número de dimensións e o tamaño:
#  o método dim() indica o numero de dimensións
#  o método size() indica o tamaño de cada dimensión


arr = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(arr) 
print(arr.dim()) # imprime 2
print(arr.size()) # imprime (2,3: 2 filas, 3 columnas
# pódese indicar a dimensión que se quere consultar
print(arr.size(dim=1)) # imprime 3

tensor([[1, 2, 3],
        [4, 5, 6]])
2
torch.Size([2, 3])
3


#### Reshape

In [35]:
array = torch.arange(1,13) # array con 12 elementos, comenzando en 1
newarr = array.reshape(4, 3) # array con 4 filas e 3 columnas
print(array)
print(newarr)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [36]:
array2 = torch.tensor([[1, 2, 3], [4, 5, 6]])

newarr = array2.reshape(-1)

print(array2)
print(newarr) 

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])
